// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWZrjrDHTH_b48IUudOm4092KzTy25Ojo',
    appId: '1:904941840518:web:c245ff215d43e8a7208907',
    messagingSenderId: '904941840518',
    projectId: 'weather-app-c6279',
    authDomain: 'weather-app-c6279.firebaseapp.com',
    storageBucket: 'weather-app-c6279.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeFfzSREvJ0HveHbQjzsW-HbC1pGg_R-o',
    appId: '1:904941840518:android:6a0cb4c7dde257b4208907',
    messagingSenderId: '904941840518',
    projectId: 'weather-app-c6279',
    storageBucket: 'weather-app-c6279.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGuSAmbMy__UhpQ5E4p9pkhvMCG1p-5JE',
    appId: '1:904941840518:ios:ca382dcb2ee262cf208907',
    messagingSenderId: '904941840518',
    projectId: 'weather-app-c6279',
    storageBucket: 'weather-app-c6279.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGuSAmbMy__UhpQ5E4p9pkhvMCG1p-5JE',
    appId: '1:904941840518:ios:ca382dcb2ee262cf208907',
    messagingSenderId: '904941840518',
    projectId: 'weather-app-c6279',
    storageBucket: 'weather-app-c6279.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWZrjrDHTH_b48IUudOm4092KzTy25Ojo',
    appId: '1:904941840518:web:824799b34c92eef0208907',
    messagingSenderId: '904941840518',
    projectId: 'weather-app-c6279',
    authDomain: 'weather-app-c6279.firebaseapp.com',
    storageBucket: 'weather-app-c6279.firebasestorage.app',
  );
}
